// vue/src/App.vue
<template>
        <DxLookup
            :data-source="dataSource"
            value-expr="ID"
            display-expr="Subject"
            search-mode="contains"
            :searchExpr="['Assignee', 'Subject']"
            :min-search-length="2"
            @value-changed="onValueChanged"
            :grouped="true"
            group-template="group-list"
            page-load-mode="nextButton"
            next-button-text="More"
            item-template="list-item"
        >
            <template #group-list="{ data }">
                {{ data.key + " - " + data.items.length }}
            </template>
            <template #list-item="{ data: itemData }">
                {{ itemData.disabled ? '\u274C ' + itemData.Subject : '\u2705 ' + itemData.Subject }}
            </template>
            <DxDropDownOptions 
                :close-on-outside-click="true"
                :show-title="false"
            />
        </DxLookup>
</template>

<script>
    import { DxLookup, DxDropDownOptions } from 'devextreme-vue/lookup';
    import DataSource from 'devextreme/data/data_source';
    import { employeesTasks } from './data';

    const dataSource = new DataSource({
        store: employeesTasks,
        key: "ID",
        group: "Assignee",
        paginate: true,
        pageSize: 2
    });

    export default {
        components: {
            DxLookup,
            DxDropDownOptions
        },
        data() {
            return {
                dataSource
            }
        },
        methods: {
            onValueChanged(e) {
                console.log(e.previousValue);
                console.log(e.value);
            }
        }
    }
</script>

// react/src/App.js
import React from 'react';
 
import 'devextreme/dist/css/dx.light.css';
 
import { DropDownOptions, Lookup } from 'devextreme-react/lookup';
 
import DataSource from 'devextreme/data/data_source';
import { employeesTasks } from './data';
 
const dataSource = new DataSource({
    store: employeesTasks,
    key: "ID",
    group: "Assignee",
    paginate: true,
    pageSize: 2
});

const searchExpression = ['Assignee', 'Subject'];

const renderListGroup = (data) => {
    return (
        <div>{ data.key + " - " + data.items.length }</div>
    );
}

const renderListItem = (data) => {
    return (
        <div>{ data.disabled ? '\u274C ' + data.Subject : '\u2705 ' + data.Subject }</div>
    );
}

function App() {
    const onValueChanged = useCallback((e) => {
        console.log(e.previousValue);
        console.log(e.value);
    }, []);

    return (
        <Lookup
            dataSource={dataSource}
            valueExpr="ID"
            displayExpr="Subject"
            searchMode="contains"
            searchExpr={searchExpression}
            minSearchLength={2}
            onValueChanged={onValueChanged}
            grouped={true}
            groupRender={renderListGroup}
            pageLoadMode="nextButton"
            nextButtonText="More"
            itemRender={renderListItem}
        >
            <DropDownOptions
                closeOnOutsideClick={true}
                showTitle={false}
            />
        </Lookup>
    ); 
}
 
export default App;
