// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Service, Task } from './app.service';
import DataSource from 'devextreme/data/data_source';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service],
})
export class AppComponent {
  employeesTasks: Task[];
  dataSource: DataSource;

  constructor(service: Service) {
    this.employeesTasks = service.getTasks();
    this.dataSource = new DataSource({
      store: this.employeesTasks,
      key: "ID",
      group: "Assignee",
      paginate: true,
      pageSize: 2
    });
  }

  onValueChanged(e: any) {
    console.log(e.previousValue);
    console.log(e.value);
  }

  groupTemplate(data: any) {
    let countInvisible = 0;
      for (let i = 0; i < data.items.length; i++) {
        if (data.items[i].visible === false) {
          countInvisible += 1;
        }
      }
    return data.key + " (" + (data.items.length - countInvisible) + " tasks)";
  }
}

<div id="container">
    <dx-lookup
        [dataSource]="dataSource"
        valueExpr="ID"
        displayExpr="Subject"
        searchMode="contains"
        [searchExpr]="['Assignee', 'Subject']"
        [minSearchLength]="2"
        [showDataBeforeSearch]="true"
        (onValueChanged)="onValueChanged($event)"
        [grouped]="true"
        groupTemplate="listGroup"
        pageLoadMode="nextButton"
        nextButtonText="More"
        itemTemplate="listItem"
    >
        <dxo-drop-down-options 
            closeOnOutsideClick="true"
            [showTitle]="false"
        >
        </dxo-drop-down-options>
        <div *dxTemplate="let data of 'listGroup'">
            {{ groupTemplate(data) }}
        </div>
        <div *dxTemplate="let itemData of 'listItem'">
            {{ itemData.disabled ? '\u274C ' + itemData.Subject : '\u2705 ' + itemData.Subject }}
        </div>
    </dx-lookup>
</div>

// react/src/App.js
import React, { useCallback } from 'react';
 
import 'devextreme/dist/css/dx.light.css';
 
import { DropDownOptions, Lookup } from 'devextreme-react/lookup';
 
import DataSource from 'devextreme/data/data_source';
import { employeesTasks } from './data';
 
const dataSource = new DataSource({
    store: employeesTasks,
    key: "ID",
    group: "Assignee",
    paginate: true,
    pageSize: 2
});

const searchExpression = ['Assignee', 'Subject'];

const renderListGroup = (data) => {
    let countInvisible = 0;
    for (let i = 0; i < data.items.length; i++) {
        if (data.items[i].visible === false) {
            countInvisible += 1;
        }
    }        
    return (
        <div>{ data.key + " (" + (data.items.length - countInvisible) + " tasks)" }</div>
    );
}

const renderListItem = (data) => {
    return (
        <div>{ data.disabled ? '\u274C ' + data.Subject : '\u2705 ' + data.Subject }</div>
    );
}

function App() {
    const onValueChanged = useCallback((e) => {
        console.log(e.previousValue);
        console.log(e.value);
    }, []);

    return (
        <div id="container">
            <Lookup
                dataSource={dataSource}
                valueExpr="ID"
                displayExpr="Subject"
                searchMode="contains"
                searchExpr={searchExpression}
                minSearchLength={2}
                showDataBeforeSearch={true}
                onValueChanged={onValueChanged}
                grouped={true}
                groupRender={renderListGroup}
                pageLoadMode="nextButton"
                nextButtonText="More"
                itemRender={renderListItem}
            >
                <DropDownOptions
                    closeOnOutsideClick={true}
                    showTitle={false}
                />
            </Lookup>
        </div>
    ); 
}
 
export default App;
